### ISSUE TITLE
AttributeError: ''DeleteObsoleteProjectPackagesJob'' object has no attribute ''job''

### ISSUE THREAD

**Issue by qwenger** [opengisch/QFieldCloud#1190]
```
db-1                           | 2025-03-28 13:21:37.984 UTC [35] LOG:  statement: INSERT INTO "django_cron_cronjoblog" ("code", "start_time", "end_time", "is_success", "message", "ran_at_time") VALUES ('qfieldcloud.delete_obsolete_project_packages', '2025-03-28T14:21:37.977800+01:00'::timestamptz, '2025-03-28T14:21:37.984350+01:00'::timestamptz, false, 'Traceback (most recent call last):
db-1                           |          File "/usr/local/lib/python3.10/site-packages/django_cron/management/commands/runcrons.py", line 82, in run_cron_with_cache_check
db-1                           |            manager.run(force)
db-1                           |          File "/usr/local/lib/python3.10/site-packages/django_cron/__init__.py", line 282, in run
db-1                           |            self.msg = self.cron_job.do()
db-1                           |          File "/usr/src/app/qfieldcloud/core/cron.py", line 121, in do
db-1                           |            if self.job.project.uses_legacy_storage:
db-1                           |        AttributeError: ''DeleteObsoleteProjectPackagesJob'' object has no attribute ''job''
db-1                           |
db-1                           |        ', NULL) RETURNING "django_cron_cronjoblog"."id"
```

Bug introduced in 65819ba371b58cd3739ade9d912d2e687a5fec9f.

Unclear to me what was meant there, as neither `DeleteObsoleteProjectPackagesJob` nor `django_cron.CronJobBase` seem to ever have had an attribute `job`.

Note that it also affects https://github.com/opengisch/QFieldCloud/blob/e278ae256255571eeed3f335dfb135fd243489a3/docker-app/qfieldcloud/core/cron.py#L138.

**Comment by gounux** [comment]
Thanks @qwenger for spotting this. Should be fixed by #1194 .
